collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.3259935
color:
  saturation: 0.7019334
  lightness: 1
  brandStrength: 0.6918008
  rhythmicContrast: 1
layout_spectrum: 1
name: The Grid Beta
