favicon: null
name: The Grid Beta
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.1875
  brandStrength: 0.5625
  lightness: 0.9375
  brandColors:
    - '#ffffff'
    - '#161a25'
    - '#6d97df'
    - '#5e5747'
    - '#a08957'
  rhythmicContrast: 0.2744361
typography_spectrum: 0.5497
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.99901
analytics:
  twitter: null
  google: null
  facebook: null
