name: The Grid Beta
favicon: null
layout_spectrum: 0.99901
typography_spectrum: 0.5497
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#161a25'
    - '#6d97df'
    - '#5e5747'
    - '#a08957'
  brandStrength: 0.5625
  lightness: 0.9375
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
