collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.7019334
  brandStrength: 0.6918008
  lightness: 0
  rhythmicContrast: 0.3216971
typography_spectrum: 0.3259935
layout_spectrum: 1
name: The Grid Beta
