layout_spectrum: 0.2764861
color:
  saturation: 0.01927292
  brandStrength: 0.6918008
  lightness: 0
  rhythmicContrast: 0.8806587
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
typography_spectrum: 0.8328524
name: The Grid Beta
